language: julia

os:
  - linux
#  - osx
#  - windows

julia:
  - 1.2
  #- 1.3
#  - 1.4
  - 1.5
#  - nightly

jobs:
  allow_failures:
  - julia: nightly

after_success:
  - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder());  Codecov.submit(process_folder())'

notifications:
  email: false

addons:
  apt_packages:
    - gfortran
