language: julia

sudo: required

os:
  - linux
  #- osx

julia:
  - 1.2
  - 1.3
  - nightly

matrix:
  allow_failures:
  - julia: nightly

notifications:
  email: false

addons:
  apt_packages:
    - gfortran
